###

POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Vendor",
  "role": "VENDOR",
  "email": "vendor@example.com",
  "password": "password123",
  "phoneNumber": "9819121547"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "vendorme@example.com",
  "password": "password123"
}

###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Test USER",
  "role": "USER",
  "email": "vinayak@gmail.com",
  "password": "password123",
  "phone_number": "9819121547"
}

### 
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "vinayak@gmail.com",
  "password": "password123"
}